"""initial schema

Revision ID: 527c4f3ff130
Revises: 
Create Date: 2026-09-07 10:53:18.911482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '527c4f3ff130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendance_summary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('first_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_seconds', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_employee_date')
    )
    op.create_index(op.f('ix_daily_attendance_summary_employee_id'), 'daily_attendance_summary', ['employee_id'], unique=False)
    op.create_index(op.f('ix_daily_attendance_summary_work_date'), 'daily_attendance_summary', ['work_date'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provisioning_token_hash', sa.String(length=64), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_access_token_hash'), 'devices', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_site_id'), 'employees', ['site_id'], unique=False)
    op.create_table('gallery_changes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_changes_employee_id'), 'gallery_changes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_gallery_changes_site_id'), 'gallery_changes', ['site_id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('device_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_event_id', name='uq_device_event')
    )
    op.create_index(op.f('ix_attendance_events_device_id'), 'attendance_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_employee_id'), 'attendance_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_outcome'), 'attendance_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_attendance_events_server_time'), 'attendance_events', ['server_time'], unique=False)
    op.create_index('ix_events_employee_time', 'attendance_events', ['employee_id', 'server_time'], unique=False)
    op.create_table('enrollment_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_images_employee_id'), 'enrollment_images', ['employee_id'], unique=False)
    op.create_index(op.f('ix_enrollment_images_sha256'), 'enrollment_images', ['sha256'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('source_image_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['enrollment_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_employee_id'), 'face_embeddings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_model_version'), 'face_embeddings', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embeddings_model_version'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_employee_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_enrollment_images_sha256'), table_name='enrollment_images')
    op.drop_index(op.f('ix_enrollment_images_employee_id'), table_name='enrollment_images')
    op.drop_table('enrollment_images')
    op.drop_index('ix_events_employee_time', table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_server_time'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_outcome'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_employee_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_device_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_gallery_changes_site_id'), table_name='gallery_changes')
    op.drop_index(op.f('ix_gallery_changes_employee_id'), table_name='gallery_changes')
    op.drop_table('gallery_changes')
    op.drop_index(op.f('ix_employees_site_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_access_token_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_daily_attendance_summary_work_date'), table_name='daily_attendance_summary')
    op.drop_index(op.f('ix_daily_attendance_summary_employee_id'), table_name='daily_attendance_summary')
    op.drop_table('daily_attendance_summary')
    # ### end Alembic commands ###
